import com.jebwerkz.dojoMaster.art.Art
import com.jebwerkz.dojoMaster.team.Team
import com.jebwerkz.dojoMaster.rank.Rank
import com.jebwerkz.dojoMaster.rank.RankTitle
import com.jebwerkz.dojoMaster.rank.Color
import com.jebwerkz.dojoMaster.curriculum.Level
import com.jebwerkz.dojoMaster.User
import com.jebwerkz.dojoMaster.UserRole
import com.jebwerkz.dojoMaster.Role
import com.jebwerkz.dojoMaster.person.Person

import java.text.SimpleDateFormat

class BootStrap {

    def sdf = new SimpleDateFormat("MM/dd/yyyy")
    
    def init = { servletContext ->
    
        if(!Role.count()){
            def adminRole = new Role(authority: 'ROLE_ADMIN').save(flush: true)
            def userRole = new Role(authority: 'ROLE_USER').save(flush: true)
            def instructorRole = new Role(authority: 'ROLE_INSTRUCTOR').save(flush:true)

            def testUser = new User(username: 'admin', enabled: true, password: 'admin')
            testUser.save(flush:true)

            UserRole.create testUser, adminRole, true
            UserRole.create testUser, userRole, true
        }

        if(!Art.count()) {
            new Art(name:"Taekwondo", nameKr:"태권도", description:"Korean art: The Way of Hand and Foot").save(failOnError: true)
            new Art(name:"Hapkido", nameKr:"합기도", description:"Korean art: The Way of Coordinated Power").save(failOnError: true)
            new Art(name:"Mukido", nameKr:"무기도", description:"Korean art: The Way of Weapons").save(failOnError: true)
        }

        if(!Team.count()) {
            new Team(name:"Gold Team", color:"Gold", description: "Goal Oriented Lifeskills Development", chineseCharacter: "Gold").save(failOnError: true)
            new Team(name:"Blue Team", color:"Blue", description: "Building Leaders of Unmatched Excellence", chineseCharacter: "Blue").save(failOnError: true)
        }

        if(!RankTitle.count()) {
            new RankTitle(title: "None").save(failOnError: true)
            new RankTitle(title: "Mr./Ms.").save(failOnError: true)
            new RankTitle(title: "Junior Master").save(failOnError: true)
            new RankTitle(title: "Master").save(failOnError: true)
        }

        if(!Level.count()) {
           new Level(id:1, art:1, team:1, name:"Junior White Belt").save(failOnError: true) 
           new Level(id:2, art:1, team:1, name:"Beginner").save(failOnError: true) 
           new Level(id:3, art:1, team:1, name:"Level 1").save(failOnError: true) 
           new Level(id:4, art:1, team:1, name:"Level 2").save(failOnError: true) 
           new Level(id:5, art:1, team:1, name:"Black Belt").save(failOnError: true) 
           new Level(id:6, art:2, team:1, name:"Beginner").save(failOnError: true) 
           new Level(id:7, art:2, team:1, name:"Level 1").save(failOnError: true) 
           new Level(id:8, art:2, team:1, name:"Level 2").save(failOnError: true) 
           new Level(id:9, art:2, team:1, name:"Black Belt").save(failOnError: true) 
           new Level(id:10, art:3, team:1, name:"Beginner").save(failOnError: true) 
           new Level(id:11, art:3, team:1, name:"Level 1").save(failOnError: true) 
           new Level(id:12, art:3, team:1, name:"Level 2").save(failOnError: true) 
           new Level(id:13, art:3, team:1, name:"Black Belt").save(failOnError: true) 
           new Level(id:14, art:1, team:2, name:"Student Leader").save(failOnError: true) 
           new Level(id:15, art:1, team:2, name:"Assistant").save(failOnError: true) 
           new Level(id:16, art:1, team:2, name:"Instructor").save(failOnError: true) 
           new Level(id:17, art:1, team:2, name:"Master Instructor").save(failOnError: true)
           new Level(id:18, art:2, team:2, name:"Student Leader").save(failOnError: true) 
           new Level(id:19, art:2, team:2, name:"Assistant").save(failOnError: true) 
           new Level(id:20, art:2, team:2, name:"Instructor").save(failOnError: true) 
           new Level(id:21, art:2, team:2, name:"Master Instructor").save(failOnError: true)
           new Level(id:22, art:3, team:2, name:"Student Leader").save(failOnError: true) 
           new Level(id:23, art:3, team:2, name:"Assistant").save(failOnError: true) 
           new Level(id:24, art:3, team:2, name:"Instructor").save(failOnError: true) 
           new Level(id:25, art:3, team:2, name:"Master Instructor").save(failOnError: true)
        }

		if(!Color.count()) {
			new Color(id:1,  color:"White").save(failOnError:true)
			new Color(id:2,  color:"Yellow").save(failOnError:true)
			new Color(id:3,  color:"Orange").save(failOnError:true)
			new Color(id:4,  color:"Green").save(failOnError:true)
			new Color(id:5,  color:"Blue").save(failOnError:true)
			new Color(id:6,  color:"Brown").save(failOnError:true)
			new Color(id:7,  color:"Purple").save(failOnError:true)
			new Color(id:8,  color:"Red").save(failOnError:true)
			new Color(id:9,  color:"Black").save(failOnError:true)
			new Color(id:10, color:"Grey").save(failOnError:true)
			new Color(id:11, color:"Tan").save(failOnError:true)
			new Color(id:12, color:"Light Green").save(failOnError:true)
			new Color(id:13, color:"Light Blue").save(failOnError:true)
			new Color(id:14, color:"Navy Blue").save(failOnError:true)
		}

        if(!Rank.count()) {
        	
        	//Junior White Belt Ranks
        	new Rank(name:"White Belt", nameKr:"White Belt", art:1, team:1, level:1, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:1, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:2, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Yellow Stripe", nameKr:"Yellow Stripe", art:1, team:1, level:1, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:1, beltStripeColor:2, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:2, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Orange Stripe", nameKr:"Orange Stripe", art:1, team:1, level:1, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:1, beltStripeColor:3, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:2, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Green Stripe", nameKr:"Green Stripe", art:1, team:1, level:1, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:1, beltStripeColor:4, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:2, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Blue Stripe", nameKr:"Blue Stripe", art:1, team:1, level:1, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:1, beltStripeColor:5, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:2, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Brown Stripe", nameKr:"Brown Stripe", art:1, team:1, level:1, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:1, beltStripeColor:6, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:2, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Purple Stripe", nameKr:"Purple Stripe", art:1, team:1, level:1, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:1, beltStripeColor:7, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:2, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Double Purple Stripe", nameKr:"Double Purple Stripe", art:1, team:1, level:1, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:1, beltStripeColor:7, beltStripeCount:2, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:2, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Red Stripe", nameKr:"Red Stripe", art:1, team:1, level:1, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:1, beltStripeColor:8, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:2, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Double Red Stripe", nameKr:"Double Red Stripe", art:1, team:1, level:1, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:1, beltStripeColor:8, beltStripeCount:2, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:2, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Black Stripe", nameKr:"Black Stripe", art:1, team:1, level:1, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:1, beltStripeColor:9, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:2, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Double Black Stripe", nameKr:"Double Black Stripe", art:1, team:1, level:1, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:1, beltStripeColor:9, beltStripeCount:2, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:2, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			
			//Taekwondo Ranks
			new Rank(name:"White Belt", nameKr:"White Belt", art:1, team:1, level:2, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:1, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:2, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Yellow Belt", nameKr:"Yellow Belt", art:1, team:1, level:3, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:2, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:3, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Yellow Belt", nameKr:"Low Yellow Belt", art:1, team:1, level:3, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:2, beltStripeColor:1, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:3, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"High Yellow Belt", nameKr:"High Yellow Belt", art:1, team:1, level:3, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:2, beltStripeColor:9, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:3, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Orange Belt", nameKr:"Orange Belt", art:1, team:1, level:3, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:3, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:4, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Orange Belt", nameKr:"Low Orange Belt", art:1, team:1, level:3, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:3, beltStripeColor:1, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:4, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"High Orange Belt", nameKr:"High Orange Belt", art:1, team:1, level:3, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:3, beltStripeColor:9, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:4, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Green Belt", nameKr:"Green Belt", art:1, team:1, level:3, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:4, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:5, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Green Belt", nameKr:"Low Green Belt", art:1, team:1, level:3, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:4, beltStripeColor:1, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:5, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"High Green Belt", nameKr:"High Green Belt", art:1, team:1, level:3, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:4, beltStripeColor:9, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:5, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Blue Belt", nameKr:"Blue Belt", art:1, team:1, level:3, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:5, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:6, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Blue White Stripe", nameKr:"Low Blue White Stripe", art:1, team:1, level:3, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:5, beltStripeColor:1, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:6, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Blue Yellow Stripe", nameKr:"Low Blue Yellow Stripe", art:1, team:1, level:3, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:5, beltStripeColor:2, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:6, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Blue Orange Stripe", nameKr:"Low Blue Orange Stripe", art:1, team:1, level:3, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:5, beltStripeColor:3, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:6, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Blue Green Stripe", nameKr:"Low Blue Green Stripe", art:1, team:1, level:3, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:5, beltStripeColor:4, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:6, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Blue Brown Stripe", nameKr:"Low Blue Brown Stripe", art:1, team:1, level:3, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:5, beltStripeColor:6, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:6, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"High Blue Belt", nameKr:"High Blue Belt", art:1, team:1, level:3, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:5, beltStripeColor:9, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:6, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Brown Belt", nameKr:"Brown Belt", art:1, team:1, level:4, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:6, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:7, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Brown Belt", nameKr:"Low Brown Belt", art:1, team:1, level:4, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:6, beltStripeColor:1, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:7, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"High Borwn Belt", nameKr:"High Borwn Belt", art:1, team:1, level:4, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:6, beltStripeColor:9, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:7, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Purple Belt", nameKr:"Purple Belt", art:1, team:1, level:4, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:7, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:8, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Purple Belt", nameKr:"Low Purple Belt", art:1, team:1, level:4, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:7, beltStripeColor:1, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:8, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"High Purple Belt", nameKr:"High Purple Belt", art:1, team:1, level:4, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:7, beltStripeColor:9, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:8, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Red Belt", nameKr:"Red Belt", art:1, team:1, level:4, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:8, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Red Belt", nameKr:"Low Red Belt", art:1, team:1, level:4, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:8, beltStripeColor:1, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"High Red Belt", nameKr:"High Red Belt", art:1, team:1, level:4, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:8, beltStripeColor:9, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Reccomend Black Belt", nameKr:"Reccomend Black Belt", art:1, team:1, level:4, title:2, topColor:1, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Reccomend White Stripe", nameKr:"Low Reccomend White Stripe", art:1, team:1, level:4, title:2, topColor:1, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:1, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Reccomend Yellow Stripe", nameKr:"Low Reccomend Yellow Stripe", art:1, team:1, level:4, title:3, topColor:1, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:2, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Reccomend Orange Stripe", nameKr:"Low Reccomend Orange Stripe", art:1, team:1, level:4, title:3, topColor:1, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:3, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Reccomend Green Stripe", nameKr:"Low Reccomend Green Stripe", art:1, team:1, level:4, title:4, topColor:1, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:4, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Reccomend Blue Stripe", nameKr:"Low Reccomend Blue Stripe", art:1, team:1, level:4, title:4, topColor:1, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:5, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Low Reccomend Red Stripe", nameKr:"Low Reccomend Red Stripe", art:1, team:1, level:4, title:4, topColor:1, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:8, beltStripeCount:1, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"First Degree Black Belt", nameKr:"First Degree Black Belt", art:1, team:1, level:5, title:4, topColor:1, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:2, beltRankStripeCount:1, beltEmbroideryColor:2, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Second Degree Black Belt", nameKr:"Second Degree Black Belt", art:1, team:1, level:5, title:4, topColor:1, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:2, beltRankStripeCount:2, beltEmbroideryColor:2, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Third Degree Black Belt", nameKr:"Third Degree Black Belt", art:1, team:1, level:5, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:2, beltRankStripeCount:3, beltEmbroideryColor:2, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Fourth Degree Black Belt", nameKr:"Fourth Degree Black Belt", art:1, team:1, level:5, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:2, beltRankStripeCount:4, beltEmbroideryColor:2, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:2, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Fifth Degree Black Belt", nameKr:"Fifth Degree Black Belt", art:1, team:1, level:5, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:2, beltRankStripeCount:5, beltEmbroideryColor:2, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:2, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Sixth Degree Black Belt", nameKr:"Sixth Degree Black Belt", art:1, team:1, level:5, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:2, beltRankStripeCount:6, beltEmbroideryColor:2, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:8, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Seventh Degree Black Belt", nameKr:"Seventh Degree Black Belt", art:1, team:1, level:5, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:2, beltRankStripeCount:7, beltEmbroideryColor:2, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:8, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Eighth Degree Black Belt", nameKr:"Eighth Degree Black Belt", art:1, team:1, level:5, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:8, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:2, beltRankStripeCount:8, beltEmbroideryColor:2, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:9, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Ninth Degree Black Belt", nameKr:"Ninth Degree Black Belt", art:1, team:1, level:5, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:8, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:2, beltRankStripeCount:9, beltEmbroideryColor:2, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:9, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Tenth Degree Black Belt", nameKr:"Tenth Degree Black Belt", art:1, team:1, level:5, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:1, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:2, beltRankStripeCount:10, beltEmbroideryColor:2, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:8, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			
			//Taekwondo Blue Team Ranks
			new Rank(name:"Seonbae 1", nameKr:"Seonbae 1", art:1, team:2, level:14, title:2, topColor:null, topCollarColor:null, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:5, chevronCount:1, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Seonbae 2", nameKr:"Seonbae 2", art:1, team:2, level:14, title:2, topColor:null, topCollarColor:null, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:5, chevronCount:2, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Chosu 1", nameKr:"Chosu 1", art:1, team:2, level:15, title:2, topColor:null, topCollarColor:null, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:5, chevronCount:3, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Chosu 2", nameKr:"Chosu 2", art:1, team:2, level:15, title:2, topColor:null, topCollarColor:null, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:5, chevronCount:4, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Kyosa 1", nameKr:"Kyosa 1", art:1, team:2, level:16, title:2, topColor:5, topCollarColor:5, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:9, chevronCount:1, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Kyosa 2", nameKr:"Kyosa 2", art:1, team:2, level:16, title:2, topColor:5, topCollarColor:5, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:9, chevronCount:2, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Sabum 1", nameKr:"Sabum 1", art:1, team:2, level:17, title:2, topColor:5, topCollarColor:5, topCollarStripeColor:9, topCollarStripeCount:1, chevronColor:9, chevronCount:3, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Sabum 2", nameKr:"Sabum 2", art:1, team:2, level:17, title:2, topColor:5, topCollarColor:5, topCollarStripeColor:9, topCollarStripeCount:1, chevronColor:9, chevronCount:4, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			
			//Hapkido Ranks
			new Rank(name:"White Belt", nameKr:"White Belt", art:2, team:1, level:6, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:1, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:9, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Yellow Belt", nameKr:"Yellow Belt", art:2, team:1, level:7, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:2, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:9, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Blue Belt", nameKr:"Blue Belt", art:2, team:1, level:7, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:5, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:9, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Red Belt", nameKr:"Red Belt", art:2, team:1, level:8, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:8, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:9, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Reccomend Black Belt", nameKr:"Reccomend Black Belt", art:2, team:1, level:9, title:2, topColor:1, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"First Degree Black Belt", nameKr:"First Degree Black Belt", art:2, team:1, level:9, title:2, topColor:1, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:8, beltRankStripeCount:1, beltEmbroideryColor:8, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Second Degree Black Belt", nameKr:"Second Degree Black Belt", art:2, team:1, level:9, title:2, topColor:1, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:8, beltRankStripeCount:2, beltEmbroideryColor:8, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Third Degree Black Belt", nameKr:"Third Degree Black Belt", art:2, team:1, level:9, title:3, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:8, beltRankStripeCount:3, beltEmbroideryColor:8, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Fourth Degree Black Belt", nameKr:"Fourth Degree Black Belt", art:2, team:1, level:9, title:3, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:8, beltRankStripeCount:4, beltEmbroideryColor:8, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:2, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Fifth Degree Black Belt", nameKr:"Fifth Degree Black Belt", art:2, team:1, level:9, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:8, beltRankStripeCount:5, beltEmbroideryColor:8, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:2, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Sixth Degree Black Belt", nameKr:"Sixth Degree Black Belt", art:2, team:1, level:9, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:8, beltRankStripeCount:6, beltEmbroideryColor:8, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:8, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Seventh Degree Black Belt", nameKr:"Seventh Degree Black Belt", art:2, team:1, level:9, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:8, beltRankStripeCount:7, beltEmbroideryColor:8, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:8, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Eighth Degree Black Belt", nameKr:"Eighth Degree Black Belt", art:2, team:1, level:9, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:8, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:8, beltRankStripeCount:8, beltEmbroideryColor:8, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:9, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Ninth Degree Black Belt", nameKr:"Ninth Degree Black Belt", art:2, team:1, level:9, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:8, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:8, beltRankStripeCount:9, beltEmbroideryColor:8, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:9, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Tenth Degree Black Belt", nameKr:"Tenth Degree Black Belt", art:2, team:1, level:9, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:1, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:8, beltRankStripeCount:10, beltEmbroideryColor:8, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:8, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			
			//Hapkido Blue Team Ranks
			new Rank(name:"Seonbae 1", nameKr:"Seonbae 1", art:2, team:2, level:18, title:2, topColor:null, topCollarColor:null, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:5, chevronCount:1, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Seonbae 2", nameKr:"Seonbae 2", art:2, team:2, level:18, title:2, topColor:null, topCollarColor:null, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:5, chevronCount:2, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Chosu 1", nameKr:"Chosu 1", art:2, team:2, level:19, title:2, topColor:null, topCollarColor:null, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:5, chevronCount:3, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Chosu 2", nameKr:"Chosu 2", art:2, team:2, level:19, title:2, topColor:null, topCollarColor:null, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:5, chevronCount:4, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Kyosa 1", nameKr:"Kyosa 1", art:2, team:2, level:20, title:2, topColor:5, topCollarColor:5, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:9, chevronCount:1, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Kyosa 2", nameKr:"Kyosa 2", art:2, team:2, level:20, title:2, topColor:5, topCollarColor:5, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:9, chevronCount:2, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Sabum 1", nameKr:"Sabum 1", art:2, team:2, level:21, title:2, topColor:5, topCollarColor:5, topCollarStripeColor:9, topCollarStripeCount:1, chevronColor:9, chevronCount:3, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Sabum 2", nameKr:"Sabum 2", art:2, team:2, level:21, title:2, topColor:5, topCollarColor:5, topCollarStripeColor:9, topCollarStripeCount:1, chevronColor:9, chevronCount:4, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			
			//Mukido Ranks
			new Rank(name:"White Belt", nameKr:"White Belt", art:3, team:1, level:11, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:1, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:10, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Grey Belt", nameKr:"Grey Belt", art:3, team:1, level:11, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:10, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:11, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Tan Belt", nameKr:"Tan Belt", art:3, team:1, level:11, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:11, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:12, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Light Green Belt", nameKr:"Light Green Belt", art:3, team:1, level:11, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:1, beltColor:12, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:13, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Light Blue Belt", nameKr:"Light Blue Belt", art:3, team:1, level:12, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:13, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:5, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Blue Belt", nameKr:"Blue Belt", art:3, team:1, level:12, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:5, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:14, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Navy Blue Belt", nameKr:"Navy Blue Belt", art:3, team:1, level:12, title:1, topColor:1, topCollarColor:1, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:14, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:9, skillStripeCount:2, attitudeStripeColor:9, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Reccomend Black Belt", nameKr:"Reccomend Black Belt", art:3, team:1, level:12, title:2, topColor:1, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"First Degree Black Belt", nameKr:"First Degree Black Belt", art:3, team:1, level:13, title:2, topColor:1, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:5, beltRankStripeCount:1, beltEmbroideryColor:5, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Second Degree Black Belt", nameKr:"Second Degree Black Belt", art:3, team:1, level:13, title:2, topColor:1, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:5, beltRankStripeCount:2, beltEmbroideryColor:5, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Third Degree Black Belt", nameKr:"Third Degree Black Belt", art:3, team:1, level:13, title:3, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:5, beltRankStripeCount:3, beltEmbroideryColor:5, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Fourth Degree Black Belt", nameKr:"Fourth Degree Black Belt", art:3, team:1, level:13, title:3, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:5, beltRankStripeCount:4, beltEmbroideryColor:5, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:2, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Fifth Degree Black Belt", nameKr:"Fifth Degree Black Belt", art:3, team:1, level:13, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:5, beltRankStripeCount:5, beltEmbroideryColor:5, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:2, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Sixth Degree Black Belt", nameKr:"Sixth Degree Black Belt", art:3, team:1, level:13, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:5, beltRankStripeCount:6, beltEmbroideryColor:5, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:8, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Seventh Degree Black Belt", nameKr:"Seventh Degree Black Belt", art:3, team:1, level:13, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:9, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:5, beltRankStripeCount:7, beltEmbroideryColor:5, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:8, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Eighth Degree Black Belt", nameKr:"Eighth Degree Black Belt", art:3, team:1, level:13, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:8, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:5, beltRankStripeCount:8, beltEmbroideryColor:5, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:9, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Ninth Degree Black Belt", nameKr:"Ninth Degree Black Belt", art:3, team:1, level:13, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:8, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:5, beltRankStripeCount:9, beltEmbroideryColor:5, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:9, skillStripeColor:1, skillStripeCount:2, attitudeStripeColor:1, attitudeStripeCount:1, description:null).save(failOnError:true)
			new Rank(name:"Tenth Degree Black Belt", nameKr:"Tenth Degree Black Belt", art:3, team:1, level:13, title:4, topColor:9, topCollarColor:9, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:null, chevronCount:0, pantsColor:9, beltColor:1, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:5, beltRankStripeCount:10, beltEmbroideryColor:5, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:8, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			
			//Mukido Blue Team Ranks
			new Rank(name:"Seonbae 1", nameKr:"Seonbae 1", art:3, team:2, level:22, title:2, topColor:null, topCollarColor:null, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:5, chevronCount:1, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Seonbae 2", nameKr:"Seonbae 2", art:3, team:2, level:22, title:2, topColor:null, topCollarColor:null, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:5, chevronCount:2, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Chosu 1", nameKr:"Chosu 1", art:3, team:2, level:23, title:2, topColor:null, topCollarColor:null, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:5, chevronCount:3, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Chosu 2", nameKr:"Chosu 2", art:3, team:2, level:23, title:2, topColor:null, topCollarColor:null, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:5, chevronCount:4, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Kyosa 1", nameKr:"Kyosa 1", art:3, team:2, level:24, title:2, topColor:5, topCollarColor:5, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:9, chevronCount:1, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Kyosa 2", nameKr:"Kyosa 2", art:3, team:2, level:24, title:2, topColor:5, topCollarColor:5, topCollarStripeColor:null, topCollarStripeCount:0, chevronColor:9, chevronCount:2, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Sabum 1", nameKr:"Sabum 1", art:3, team:2, level:25, title:2, topColor:5, topCollarColor:5, topCollarStripeColor:9, topCollarStripeCount:1, chevronColor:9, chevronCount:3, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)
			new Rank(name:"Sabum 2", nameKr:"Sabum 2", art:3, team:2, level:25, title:2, topColor:5, topCollarColor:5, topCollarStripeColor:9, topCollarStripeCount:1, chevronColor:9, chevronCount:4, pantsColor:null, beltColor:null, beltStripeColor:null, beltStripeCount:0, beltRankStripeColor:null, beltRankStripeCount:0, beltEmbroideryColor:null, beltEmbroideryLeft:null, beltEmbbroideryRight:null, beltBorderColor:null, skillStripeColor:null, skillStripeCount:0, attitudeStripeColor:null, attitudeStripeCount:0, description:null).save(failOnError:true)

        }

        if(!Person.count()) {
            def jevans = new Person(firstName:"Jeremiah", lastName:"Evans", dateOfBirth: sdf.parse("06/22/1987")).save(failOnError: true)
			jevans.addToRanks(Rank.get(48))
			jevans.addToRanks(Rank.get(62))
			jevans.addToRanks(Rank.get(67))
			jevans.addToRanks(Rank.get(84))
			jevans.addToRanks(Rank.get(97))
			jevans.addToRanks(Rank.get(111))
			jevans.save(failOnError:true)
        }



    }
    def destroy = {
    }
}
